[package]
name = "depth"
version = "0.0.0"
edition = "2021"
description = "Visualize crate.io dependencies as a Tree ├──."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
